# HEY! This file is used in the dbt-utils integrations tests with GHA.
# You should __NEVER__ check credentials into version control. Thanks for reading :)

config:
  send_anonymous_usage_stats: False
  use_colors: True

dbt_metrics_integration_tests:
  target: postgres
  outputs:
    postgres:
      type: postgres
      host: "{{ env_var('POSTGRES_TEST_HOST') }}"
      user: "{{ env_var('POSTGRES_TEST_USER') }}"
      pass: "{{ env_var('POSTGRES_TEST_PASSWORD') }}"
      port: "{{ env_var('POSTGRES_TEST_PORT') | as_number }}"
      dbname: "{{ env_var('POSTGRES_TEST_DB') }}"
      schema: dbt_metrics_integration_tests
      threads: 5

    redshift:
      type: redshift
      host: "{{ env_var('REDSHIFT_TEST_HOST') }}"
      user: "{{ env_var('REDSHIFT_TEST_USER') }}"
      pass: "{{ env_var('REDSHIFT_TEST_PASS') }}"
      dbname: "{{ env_var('REDSHIFT_TEST_DBNAME') }}"
      port: "{{ env_var('REDSHIFT_TEST_PORT') | as_number }}"
      schema: dbt_metrics_integration_tests
      threads: 5

    bigquery:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('BIGQUERY_SERVICE_KEY_PATH') }}"
      project: "{{ env_var('BIGQUERY_TEST_DATABASE') }}"
      schema: dbt_metrics_integration_tests
      threads: 10

    snowflake:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_TEST_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_TEST_USER') }}"
      password: "{{ env_var('SNOWFLAKE_TEST_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_TEST_ROLE') }}"
      database: "{{ env_var('SNOWFLAKE_TEST_DATABASE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_TEST_WAREHOUSE') }}"
      schema: dbt_metrics_integration_tests
      threads: 10
