name: Continuous Integration

on:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - "main"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  postgres:
    runs-on: ubuntu-latest

    # set up env vars so that we can use them to start an instance of postgres
    env:
      POSTGRES_TEST_USER: postgres
      POSTGRES_TEST_PASSWORD: postgres
      POSTGRES_TEST_DB: gha_test
      POSTGRES_TEST_PORT: 5432
      POSTGRES_TEST_HOST: localhost

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ env.POSTGRES_TEST_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_TEST_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_TEST_DB }}
          POSTGRES_TEST_PORT: ${{ env.POSTGRES_TEST_PORT }}
          POSTGRES_TEST_HOST: ${{ env.POSTGRES_TEST_HOST }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: end-to-end-test.yml@er/clean_adding_pytest
        with:
          dbt_target: postgres
